export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const ROLLBACK_MUTATION = 'ROLLBACK_MUTATION';